create table drinks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    alcohol text not null,
    mixers text,
    liqueurs text,
    juices text,
    other text,
    instructions text not null
);